// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7jW...', // mantém o teu
    appId: '1:657870315702:web:8a639d2e073697788c4617',
    messagingSenderId: '657870315702',
    projectId: 'my-ai-chef-2025',
    authDomain: 'my-ai-chef-2025.firebaseapp.com',
    storageBucket: 'my-ai-chef-2025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7jW...',
    appId: '1:657870315702:android:1db967846083b6b08c4617',
    messagingSenderId: '657870315702',
    projectId: 'my-ai-chef-2025',
    storageBucket: 'my-ai-chef-2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7jW...',
    appId: '1:657870315702:ios:6897e523f88934bb8c4617',
    messagingSenderId: '657870315702',
    projectId: 'my-ai-chef-2025',
    storageBucket: 'my-ai-chef-2025.appspot.com',
    iosBundleId: 'com.example.myAiChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7jW...',
    appId: '1:657870315702:ios:6897e523f88934bb8c4617',
    messagingSenderId: '657870315702',
    projectId: 'my-ai-chef-2025',
    storageBucket: 'my-ai-chef-2025.appspot.com',
    iosBundleId: 'com.example.myAiChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7jW...',
    appId: '1:657870315702:web:533f9279fb2061ea8c4617',
    messagingSenderId: '657870315702',
    projectId: 'my-ai-chef-2025',
    authDomain: 'my-ai-chef-2025.firebaseapp.com',
    storageBucket: 'my-ai-chef-2025.appspot.com',
  );
}
